(define anthy-hiragana-key '("<Shift>F6"))
(define anthy-hiragana-key? (make-key-predicate '("<Shift>F6")))
(define anthy-katakana-key '("<Shift>F7"))
(define anthy-katakana-key? (make-key-predicate '("<Shift>F7")))
(define anthy-halfkana-key '("<Shift>F8"))
(define anthy-halfkana-key? (make-key-predicate '("<Shift>F8")))
(define anthy-halfwidth-alnum-key '("<Shift>F10"))
(define anthy-halfwidth-alnum-key? (make-key-predicate '("<Shift>F10")))
(define anthy-fullwidth-alnum-key '("<Shift>F9"))
(define anthy-fullwidth-alnum-key? (make-key-predicate '("<Shift>F9")))
(define anthy-kana-toggle-key '("<Shift> " "<Shift>up"))
(define anthy-kana-toggle-key? (make-key-predicate '("<Shift> " "<Shift>up")))
(define anthy-alkana-toggle-key '("<Shift>down"))
(define anthy-alkana-toggle-key? (make-key-predicate '("<Shift>down")))
(define anthy-next-prediction-key '("tab" "down" "<IgnoreCase><Control>n" "<IgnoreCase><Control>i"))
(define anthy-next-prediction-key? (make-key-predicate '("tab" "down" "<IgnoreCase><Control>n" "<IgnoreCase><Control>i")))
(define anthy-prev-prediction-key '("up" "<IgnoreCase><Control>p"))
(define anthy-prev-prediction-key? (make-key-predicate '("up" "<IgnoreCase><Control>p")))
