---
- name: Setup system
  hosts: "{{ variable_host | default('local') }}"

  vars_files:
    - vars/main.yaml

  roles:
    - role: adduser

  pre_tasks:
    - name: Updating cache
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true

  tasks:
    - name: Import installPackages
      ansible.builtin.import_tasks: tasks/installPackages.yaml
    - name: Import setupSystem
      ansible.builtin.import_tasks: tasks/setupSystem.yaml
      become: true
    - name: Import setupStardict
      ansible.builtin.import_tasks: tasks/setupStardict.yaml

    - name: Update cache and system
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
