---
- hosts: "{{ variable_host | default('local') }}"

  vars_files:
    - vars/main.yaml

  roles:
    - role: adduser

  pre_tasks:
    - name: Updating cache
      become: true
      pacman:
        update_cache: true
        upgrade: true

  tasks:
    - import_tasks: tasks/installPackages.yaml
    - import_tasks: tasks/setupSystem.yaml
      become: true
    - import_tasks: tasks/setupStardict.yaml
    # - import_tasks: tasks/setupAur.yaml
    # - import_tasks: tasks/installAndConcigureRedshift.yaml
    # - import_tasks: tasks/setupXfce.yaml

    - name: Update cache and system
      become: true
      pacman:
        update_cache: true
        upgrade: true
