---
- name: Setup aur
  hosts: "{{ variable_host | default('local') }}"

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Import setupAur
      ansible.builtin.import_tasks: tasks/setupAur.yaml

    - name: Update cache and system
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
