---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/main.yaml

  tasks:
    - import_tasks: tasks/setupAur.yaml

    - name: Update cache and system
      become: true
      pacman:
        update-cache: true
        upgrade: true
