---
- hosts: "{{ variable_host | default('local') }}"

  vars_files:
    - vars/installAurPackages.yaml
    - vars/main.yaml

  tasks:
    - name: Get number of aur installed packages
      shell: |
        set -o pipefail
        aur repo -l | wc -l
      args:
        executable: /bin/bash
      register: installed_aur_packages_number
      changed_when: false

    - include_tasks: tasks/installAurPackages.yaml
      vars:
        package: "{{ item }}"
      with_items: "{{ aur_packages_list }}"
      when: installed_aur_packages_number.stdout_lines[0] <= '3'

    # add user to group, don't forget to restart cups by "systemctl restart cups"
    - name: Add user to lp group
      become: true
      user:
        name: "{{ as_user }}"
        groups: lp
        append: true

    - name: Cound VS Code extensions already installed
      shell: |
        set -o pipefail
        code --list-extensions | wc -l
      args:
        executable: /bin/bash
      register: vs_code_extension_number
      changed_when: false

    - name: extensions to vs code
      command: "code --install-extension {{ item }}"
      with_items: "{{ vscode_extentions }}"
      when: vs_code_extension_number.stdout_lines[0] <= '5'
