---
- hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - vars/installAurPackages.yaml

  tasks:
    - include_tasks: tasks/installAurPackages.yaml
      vars:
        package: "{{ item }}"
      with_items: "{{ aur_packages_list }}"
      
    - name: extensions to vs code
      command: "code --install-extension {{ item }}"
      with_items: "{{ vscode_extentions }}"
