---
- hosts: all

  vars_files:
    - vars/main.yaml
    - vars/setupXfceLaunchers2.yaml

  tasks:
    - import_tasks: tasks/installAndConcigureRedshift.yaml
    - import_tasks: tasks/setupXfce.yaml
    - include_tasks: tasks/xfce/setupXfceLaunchers2.yaml
      vars:
        package: "{{ item }}"
      with_items: "{{ launcher_packages_list }}"
