---
- hosts: all

  vars_files:
    - vars/main.yaml

  roles:
    - role: adduser

  pre_tasks:
    - name: Updating cache
      pacman:
        update-cache: true
      become: true

  tasks:
    - import_tasks: tasks/installPackages.yaml   
    - import_tasks: tasks/installAndConcigureRedshift.yaml
    - import_tasks: tasks/setupUim.yaml
    - import_tasks: tasks/setupDefaults.yaml
    - import_tasks: tasks/setupXfce.yaml
