---
- hosts: iosim

  vars_files:
    - vars/main.yaml

  tasks:
    - import_tasks: tasks/setupAur.yaml
    - import_tasks: tasks/installAndConcigureRedshift.yaml
    - import_tasks: tasks/setupXfce.yaml

    - name: Update cache and system
      become: true
      pacman:
        update-cache: true
        upgrade: true
