---
- debug:
    var: package

- name: "Get {{ package }} depedencies"
  command: "aur depends -a {{ package }}"
  register: aur_packages_depedencies
  changed_when: false

- debug:
    var: aur_packages_depedencies.stdout_lines[0:-1]

- name: Install depedencies except last one, which is AUR package itself
  become: true
  pacman:
    name: "{{ aur_packages_depedencies.stdout_lines[0:-1] }}"

- name: "Sync package {{ package }}"
  command: "aur sync --noview {{ package }}"
  changed_when: true

- name: "Install package {{ package }}"
  become: true
  pacman:
    name: "{{ package }}"
    state: present

# add user to group, don't forget to restart cups by "systemctl restart cups"
- name: Add user to lp group
  become: true
  user:
    name: "{{ as_user }}"
    groups: lp
    append: true
