---
- name: Debug
  debug:
    var: package

- name: "Get {{ package }} depedencies"
  command: "aur depends -a {{ package }}"
  register: aur_packages_depedencies
  changed_when: false

- name: Debug
  debug:
    var: aur_packages_depedencies.stdout_lines[0:-1]

- name: Install depedencies except last one, which is AUR package itself
  become: true
  pacman:
    name: "{{ aur_packages_depedencies.stdout_lines[0:-1] }}"

- name: "Sync package {{ package }}"
  command: "aur sync --noview {{ package }}"
  changed_when: true

- name: "Install package {{ package }}"
  become: true
  pacman:
    name: "{{ package }}"
    state: present
