---
- name: Debug
  debug:
    var: package

- name: "Get {{ package }} depedencies"
  command: "aur depends -a {{ package }}"
  register: aur_packages_depedencies
  changed_when: false

- name: Debug dependencies
  debug:
    var: aur_packages_depedencies.stdout_lines

- name: Debug
  debug:
    msg: "{{ item_debug | split(\"\t\") | last }}"
  loop: "{{ aur_packages_depedencies.stdout_lines }}"
  loop_control:
    loop_var: item_debug
  when: "package.find(\"{{ item_debug | split(\"\t\") | last }}\") == -1"

- name: Install depedencies except last one, which is AUR package itself
  become: true
  pacman:
    name: "{{ item_aur | split(\"\t\") | last }}"
  loop: "{{ aur_packages_depedencies.stdout_lines }}"
  loop_control:
    loop_var: item_aur
  when: "package.find(\"{{ item_aur | split(\"\t\") | last }}\") == -1"

- name: "Sync package {{ package }}"
  command: "aur sync --noview {{ package }}"
  changed_when: true

- name: "Install package {{ package }}"
  become: true
  pacman:
    name: "{{ package }}"
    state: present
