---
- name: Install redshift
  become: true
  community.general.pacman:
    name: redshift
    state: present

- name: Make sure the .config directory is present
  ansible.builtin.file:
    path: "{{ config_redshift_dest_path_dir }}"
    state: directory
    mode: 0744

- name: Make sure the destination directory for redshift config is present
  ansible.builtin.file:
    path: "{{ config_redshift_dest_path }}"
    state: directory
    mode: 0744

- name: Copy config file
  ansible.builtin.copy:
    src: "{{ config_redshift_src_file }}"
    dest: "{{ config_redshift_dest_path }}/config"
    mode: 0644
