---
- name: Load list of variables
  include_vars:
    file: vars/setupAur.yaml

- name: Load list of variables
  include_vars:
    file: vars/main.yaml

- name: Import installAur
  ansible.builtin.import_tasks: tasks/aur/installAur.yaml
