---
- name: Setup timezone
  command: ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime

- name: Setup hostname
  command: "echo IO > /etc/hostname"

- name: Copy fstab
  become: true
  copy:
    src: files/fstab
    dest: /etc/fstab

- name: Copy .bashrc
  become: true
  copy:
    src: files/.bashrc
    dest: ~/

- name: Set global PS1
  lineinfile:
    dest: "/etc/bash.bashrc"
    regexp: "^PS1="
    line: "PS1='[\\u@\\h \\w]\\$ '"
    state: present

- name: Set global ls alias
  lineinfile:
    dest: "/etc/bash.bashrc"
    regexp: "alias ls="
    line: "alias ls='ls --color=auto'"
    state: present

- name: Setup audio sink
  become: true
  blockinfile:
    path: /etc/pulse/default.pa
    marker: ""
    marker_begin: ""
    marker_end: ""
    block: |
      set-default-sink alsa_output.pci-0000_00_1b.0.analog-stereo
