- name: reset all panels
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  command: xfconf-query -c xfce4-panel -r -R -p /panels

- name: reset all plugins
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  command: xfconf-query -c xfce4-panel -r -R -p /plugins

- name: make 5 panels
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels"
    value_type: "int"
    value: "1,2,3,4,5"

- import_tasks: tasks/xfce/setupXfceGeneral.yaml
- import_tasks: tasks/xfce/setupXfceMiscellaneous.yaml
- import_tasks: tasks/xfce/setupXfcePlugins.yaml
- import_tasks: tasks/xfce/setupXfcePanel1.yaml
- import_tasks: tasks/xfce/setupXfcePanel2.yaml
- import_tasks: tasks/xfce/setupXfcePanel3.yaml
- import_tasks: tasks/xfce/setupXfcePanel4.yaml
- import_tasks: tasks/xfce/setupXfcePanel5.yaml
- import_tasks: tasks/xfce/setupXfceKeyboard.yaml
