---
- name: Setup timezone
  # command: ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Prague
    dest: /etc/localtime
    state: link

- name: Setup hostname
  become: true
  ansible.builtin.command: "echo IO > /etc/hostname"
  changed_when: true

# - name: Copy fstab
#   become: true
#   copy:
#     src: files/fstab
#     dest: /etc/fstab

- name: Copy .bashrc
  become: true
  ansible.builtin.copy:
    src: files/.bashrc
    dest: ~/
    mode: 0755

- name: Set global PS1
  ansible.builtin.lineinfile:
    dest: "/etc/bash.bashrc"
    regexp: "^PS1="
    line: "PS1='[\\u@\\h \\w]\\$ '"
    state: present

- name: Set global ls alias
  ansible.builtin.lineinfile:
    dest: "/etc/bash.bashrc"
    regexp: "alias ls="
    line: "alias ls='ls --color=auto'"
    state: present

# - name: Setup audio sink
#   become: true
#   blockinfile:
#     path: /etc/pulse/default.pa
#     marker: ""
#     marker_begin: ""
#     marker_end: ""
#     block: |
#       set-default-sink alsa_output.pci-0000_00_1b.0.analog-stereo
