---
- name: Create repo directory
  become: true
  file:
    path: "{{ repo_dir }}"
    state: directory
    owner: "{{ as_user }}"
    group: "{{ uid_guid }}"
    mode: 0744

- name: Does repo db already exists?
  stat:
    path: "{{ repo_dir }}/{{ repo_name }}"
  register: repodbstate

- name: Create repo db
  command: "repo-add {{ repo_dir }}/{{ repo_name }}"
  when: not repodbstate.stat.exists

- name: Read pacman.conf
  become: true
  slurp:
    src: "/etc/pacman.conf"
  register: pacmanconf

- name: Is pacman.conf configured?
  set_fact:
    aurrepoconf: "{{ pacmanconf['content'] | b64decode | regex_findall('aur_repo') }}"

- debug:
    var: aurrepoconf

- debug:
    var: not aurrepoconf

- name: Insert configuration for aur repo into pacman.conf
  become: true
  blockinfile:
    path: /etc/pacman.conf
    marker: ""
    marker_begin: ""
    marker_end: ""
    block: |
      [aur_repo]
      SigLevel = Optional TrustAll
      Server = file:///opt/aur_repo
  when: not aurrepoconf

- name: Updating cache
  become: true
  pacman:
    update-cache: true
