---
- name: Reboot
  hosts: iosim

  tasks:
    - name: Reboot immediately.
      become: true
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      changed_when: false

    - name: Wait for the reboot to complete.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
