---
- hosts: iosim

  vars_files:
    - ../vars/main.yaml

  tasks:
    - name: Create getty@tty1.service.d directory
      become: true
      file:
        path: "/etc/systemd/system/getty@tty1.service.d"
        state: directory

    - name: Copy autologin config
      become: true
      template:
        src: skip-prompt.conf.j2
        dest: "/etc/systemd/system/getty@tty1.service.d/skip-prompt.conf"

    - name: Autostart xorg after login
      # become: true
      # become_user: "{{ as_user }}"
      blockinfile:
        path: "/home/{{ as_user }}/.bash_profile"
        # marker: ""
        # marker_begin: ""
        # marker_end: ""
        block: |
          if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
            exec startxfce4
          fi
