---
name: 'Vagrant-VirtualBox-with-repos-Vagrantfile'
description: 'Run CI in VirtualBox for GitHub Actions'
inputs:
  run:
    description: 'the commands to run in vm'
    required: true
branding:
  icon: 'activity'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - run: |
        run() {
          printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
          $@
        }
        WORK_DIR=$(mktemp -d)

        run cd "$WORK_DIR"

        pwd && ls
        echo 'set -e' >> shell.sh
        export -p | grep 'GITHUB_' >> shell.sh
        echo "cd /home/vagrant/${GITHUB_REPOSITORY}" >> shell.sh
        cat >> shell.sh <<'EOF'
        run() {
          printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
          $@
        }

        ${{inputs.run}}
        EOF

        sed -i -e 's/config.vm.synced_folder.*/config.vm.synced_folder "${GITHUB_WORKSPACE}", "\/home\/vagrant\/${GITHUB_REPOSITORY}", type: "rsync"/g' Vagrantfile

        run cat Vagrantfile
        run cat shell.sh

        run vagrant up --provision
      shell: bash
