---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    # Can be any supported provider (VBox, Parallels, libvirt, etc)
    name: libvirt

platforms:
  - name: instance
    # List of dictionaries mapped to `config.vm.network`
    interfaces:
      # `network_name` is the required identifier, all other keys map to
      # arguments.
      - network_name: forwarded_port
        guest: 80
        host: 8080
    # List of raw Vagrant `config` options
    instance_raw_config_args:
      - vagrant.plugins = ["vagrant-libvirt"]
      # use single quotes to avoid YAML parsing as dict due to ':'
      - 'vm.synced_folder ".", "/vagrant", type: "rsync"'
    # Dictionary of `config` options. Note that string values need to be
    # explicitly enclosed in quotes.
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: true
    box: archlinux/archlinux
    box_version: 20201215.11392
    box_url:
    memory: 1024
    cpus: 1
    # Dictionary of options passed to the provider
    provider_options:
      video_type: 'vga'
    # List of raw provider options
    provider_raw_config_args:
      - cpuset = '1-4,^3,6'
    provision: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
verifier:
  name: ansible
