---
- name: "{{ item.property }} - {{ item.subproperty }}"
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
  - { property: 'plugin-2', subproperty: "/autohide-behavior", type: int, value: "2" }
  - { property: 'plugin-2', subproperty: "/mode", type: int, value: "2" }
  - { property: 'plugin-2', subproperty: "/plugin-ids", type: int, value: "16,15,20,21,25,22,42,24,26,27,28,29,30,31,32,34,33,8,35,36,37,43" }
  - { property: 'plugin-2', subproperty: "/position", type: string, value: "p=1;x=3807;y=554" }
  - { property: 'plugin-2', subproperty: "/position-locked", type: bool, value: "TRUE" }
  - { property: 'plugin-2', subproperty: "/size", type: int, value: "64" }

