---
- name: "Setup xsettings"
  community.general.xfconf:
    channel: "xsettings"
    property: "/Gtk/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - { property: 'CursorThemeName', subproperty: "", type: string, value: "Adwaita" }
    - { property: 'CursorThemeSize', subproperty: "", type: int, value: "0" }

- name: "Setup theme and icon theme"
  community.general.xfconf:
    channel: "xsettings"
    property: "/Net/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - { property: 'IconThemeName', subproperty: "", type: string, value: "Adwaita" }
    - { property: 'ThemeName', subproperty: "", type: string, value: "Adwaita-dark" }
