---
- name: "Setting up Panel-5 Bottom"
  community.general.xfconf:
    channel: "xfce4-panel"
    property: "/panels/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - { property: 'panel-5', subproperty: "/autohide-behavior", type: int, value: "2" }
    - { property: 'panel-5', subproperty: "/background-style", type: int, value: "0" }
    - { property: 'panel-5', subproperty: "/mode", type: int, value: "0" }
    - { property: 'panel-5', subproperty: "/position", type: string, value: "p=12;x=2948;y=1055" }
    - { property: 'panel-5', subproperty: "/size", type: int, value: "48" }
