---
- name: "Copy {{ item.filename }}"
  copy: 
    src: "files/{{ item.filename }}"
    dest: ~/
  with_items:
  - { filename: '.Xdefaults'}
  - { filename: '.xinitrc'}
  - { filename: '.bashrc'}
  - { filename: '.gitconfig'}