---
- name: "Copy {{ item.filename }}"
  ansible.builtin.copy:
    src: "files/{{ item.filename }}"
    dest: ~/
    mode: 0755
  with_items:
    - { filename: '.Xdefaults'}
    - { filename: '.xinitrc'}
    - { filename: '.bashrc'}
    - { filename: '.gitconfig'}
