---
- name: plugin-56 launcher
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/plugin-56"
    value_type: "string"
    value: "launcher"

- name: plugin-56-items
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/plugin-56/items"
    value_type: "string"
    value: "15986816841.desktop"
    force_array: true

- name: plugin-7 launcher
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/plugin-7"
    value_type: "string"
    value: "launcher"

- name: plugin-7-items
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/plugin-7/items"
    value_type: "string"
    value: "15817800231.desktop"
    force_array: true
