---
- name: panel-2 set autohide-behavior
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-2/autohide-behavior"
    value_type: "int"
    value: "2"

- name: panel-2 set mode
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-2/mode"
    value_type: "int"
    value: "2"

- name: panel-2 set plugin-ids
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-2/plugin-ids"
    value_type: "int"
    value: "16,15,20,21,25,22,42,24,26,27,28,29,30,31,32,34,33,8,35,36,37,43"

- name: panel-2 set position
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-2/position"
    value_type: "string"
    value: "p=1;x=3807;y=554"

- name: panel-2 set position-locked
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-2/position-locked"
    value_type: "bool"
    value: "TRUE"

- name: panel-2 set size
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-2/size"
    value_type: "int"
    value: "64"
