---
- name: "{{ item.property }} - {{ item.subproperty }}"
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
  - { property: 'plugin-3', subproperty: "/autohide-behavior", type: int, value: "2" }
  - { property: 'plugin-3', subproperty: "/length", type: int, value: "1" }
  - { property: 'plugin-3', subproperty: "/plugin-ids", type: string, value: "7,4,56" }
  - { property: 'plugin-3', subproperty: "/position", type: string, value: "p=6;x=104;y=28" }
  - { property: 'plugin-3', subproperty: "/position-locked", type: BOOL, value: "TRUE" }
  - { property: 'plugin-3', subproperty: "/size", type: int, value: "48" }
