---
- name: panel-5 set autohide-behavior
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-5/autohide-behavior"
    value_type: "int"
    value: "2"


# - name: panel-5 set plugin-ids
# #   become: true
# #   become_user: "{{ as_user }}"
# #   environment:
# #     DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
#   xfconf:
#     channel: "xfce4-panel"
#     property: "/panels/panel-5/plugin-ids"
#     value_type: "int"
#     value: "19"
#     force_array: true

- name: panel-5 set position
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-5/position"
    value_type: "string"
    value: "p=10;x=2948;y=1055"

# - name: panel-5 set position-locked
# #   become: true
# #   become_user: "{{ as_user }}"
# #   environment:
# #     DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
#   xfconf:
#     channel: "xfce4-panel"
#     property: "/panels/panel-5/position-locked"
#     value_type: "bool"
#     value: "TRUE"

- name: panel-5 set size
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-5/size"
    value_type: "int"
    value: "48"
