---
- name: panel set autohide-behavior
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/autohide-behavior"
    value_type: "int"
    value: "2"

- name: panel set backgroud-style
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/background-style"
    value_type: "int"
    value: "0"

- name: panel set enter-opacity
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/enter-opacity"
    value_type: "int"
    value: "100"

- name: panel set icon-size
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/icon-size"
    value_type: "int"
    value: "16"

- name: panel set leave-opacity
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/leave-opacity"
    value_type: "int"
    value: "100"

- name: panel set length
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/length"
    value_type: "int"
    value: "50"

- name: panel set length-adjust
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/length-adjust"
    value_type: "bool"
    value: "FALSE"

- name: panel set mode
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/mode"
    value_type: "int"
    value: "0"

- name: panel set nrows
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/nrows"
    value_type: "int"
    value: "1"

- name: panel set plugin-ids
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/plugin-ids"
    value_type: "int"
    value: "1,2,3,5,6,11,12,13,14"

- name: panel set position
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/position"
    value_type: "string"
    value: "p=2;x=3438;y=19"

- name: panel set position-locked
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/position-locked"
    value_type: "bool"
    value: "TRUE"

- name: panel set size
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/size"
    value_type: "int"
    value: "26"

- name: panel set span-monitors
  become: true
  become_user: "{{ as_user }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-1/span-monitors"
    value_type: "bool"
    value: "FALSE"
