---
- name: "{{ item.property }} - {{ item.subproperty }}"
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
  - { property: 'plugin-4', subproperty: "/autohide-behavior", type: int, value: "2" }
  - { property: 'plugin-4', subproperty: "/length", type: int, value: "10" }
  - { property: 'plugin-4', subproperty: "/mode", type: int, value: "1" }
  - { property: 'plugin-4', subproperty: "/nrows", type: int, value: "2" }
  - { property: 'plugin-4', subproperty: "/position", type: string, value: "p=7;x=26;y=728" }
  - { property: 'plugin-4', subproperty: "/position-locked", type: bool, value: "TRUE" }
  - { property: 'plugin-4', subproperty: "/size", type: int, value: "48" }
  - { property: 'plugin-4', subproperty: "/span-monitors", type: bool, value: "FALSE" }

- name: panel-4 set plugin-ids
  # become: true
  # become_user: "{{ as_user }}"
  # environment:
    # DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{uid_guid}}/bus
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/panel-4/plugin-ids"
    value_type: "int"
    value: "19"
    force_array: true
