---
- name: Remove some /commands/custom shortcuts
  community.general.xfconf:
    channel: "xfce4-keyboard-shortcuts"
    property: "/commands/custom/{{ item.property }}"
    value_type: "string"
    value: "{{ item.value }}"
    state: absent
  with_items:
    - { property: "<Alt>F1", value: ""}
    - { property: "<Alt>F2", value: ""}
    - { property: "<Alt>F3", value: ""}

- name: Remove some /commands/default shortcuts
  community.general.xfconf:
    channel: "xfce4-keyboard-shortcuts"
    property: "/commands/default/{{ item.property }}"
    value_type: "string"
    value: "{{ item.value }}"
    state: absent
  with_items:
    - { property: "<Alt>F1", value: ""}
    - { property: "<Alt>F2", value: ""}
    - { property: "<Alt>F3", value: ""}

- name: Setup custom keyboard shortcuts
  community.general.xfconf:
    channel: "xfce4-keyboard-shortcuts"
    property: "/commands/custom/{{ item.property }}"
    value_type: "string"
    value: "{{ item.value }}"
  with_items:
    - { property: "<Alt>a", value: "ssh-agent xterm"}
    - { property: "<Alt>b", value: "keepassxc"}
    - { property: "<Alt>d", value: "thunar"}
    - { property: "<Alt>e", value: "google-chrome-stable"}
    - { property: "<Alt>n", value: "deluge"}
    - { property: "<Alt>q", value: "audacious"}
    - { property: "<Alt>r", value: "xfrun4"}
    - { property: "<Alt>s", value: "stardict"}
    - { property: "<Alt>w", value: "firefox"}
    - { property: "<Alt>u", value: "xterm -geometry 159x40"}
    - { property: "<Alt>y", value: "xterm -geometry 159x25"}
    - { property: "<Alt>t", value: "evince"}
    - { property: "<Alt>f", value: "code"}
    - { property: "<Alt>g", value: "/opt/Rider/bin/rider.sh"}
    - { property: "<Alt>z", value: "teams"}
    - { property: "<Super>l", value: "xflock4"}
    - { property: "<Super>p", value: "xfce4-display-settings --minimal"}
    - { property: "<Control><Alt>Delete", value: "xflock4"}
    - { property: "<Primary>Escape", value: "xfdesktop --menu"}
    - { property: "Print", value: "xfce4-screenshooter"}
    - { property: "<Alt>Print", value: "xfce4-screenshooter -w"}
    - { property: "<Shift>Print", value: "xfce4-screenshooter -r"}
    - { property: "AudioLowerVolume", value: "pamixer -d 2"}
    - { property: "AudioMute", value: "pamixer -t"}
    - { property: "AudioRaiseVolume", value: "pamixer -i 2"}
    - { property: "Calculator", value: "gnome-calculator"}
    - { property: "Search", value: "xfce4-settings-manager"}
    - { property: "HomePage", value: "google-chrome-stable"}

- name: Remove some /xfwm4/custom shortcuts
  community.general.xfconf:
    channel: "xfce4-keyboard-shortcuts"
    property: "/xfwm4/custom/{{ item.property }}"
    value_type: "string"
    value: "{{ item.value }}"
    state: absent
  with_items:
    - { property: "<Primary>F1", value: "workspace_1_key"}
    - { property: "<Primary>F2", value: "workspace_2_key"}
    - { property: "<Primary>F3", value: "workspace_3_key"}
    - { property: "<Primary>F4", value: "workspace_4_key"}
    - { property: "<Primary>F5", value: "workspace_5_key"}
    - { property: "<Primary>F6", value: "workspace_6_key"}
    - { property: "<Primary>F7", value: "workspace_7_key"}
    - { property: "<Primary>F8", value: "workspace_8_key"}
    - { property: "<Primary>F9", value: "workspace_9_key"}
    - { property: "<Primary>F10", value: "workspace_10_key"}
    - { property: "<Primary>F11", value: "workspace_11_key"}
    - { property: "<Primary>F12", value: "workspace_12_key"}

- name: Setup xfce4 keyboard shortcuts
  community.general.xfconf:
    channel: "xfce4-keyboard-shortcuts"
    property: "/xfwm4/custom/{{ item.property }}"
    value_type: "string"
    value: "{{ item.value }}"
  with_items:
    - { property: "<Alt>F1", value: "workspace_1_key"}
    - { property: "<Alt>F2", value: "workspace_2_key"}
    - { property: "<Alt>F3", value: "workspace_3_key"}
    - { property: "<Alt>F4", value: "workspace_4_key"}
    - { property: "<Alt>F5", value: "workspace_5_key"}
    - { property: "<Alt>F6", value: "workspace_6_key"}
    - { property: "<Alt>F7", value: "workspace_7_key"}
    - { property: "<Alt>F8", value: "workspace_8_key"}
    - { property: "<Alt>F9", value: "workspace_9_key"}
    - { property: "<Alt>F10", value: "workspace_10_key"}
    - { property: "<Alt>F11", value: "workspace_11_key"}
    - { property: "<Alt>F12", value: "workspace_12_key"}
    - { property: "<Alt>c", value: "close_window_key"}
    - { property: "<Alt>v", value: "maximize_window_key"}
    - { property: "<Alt>x", value: "stick_window_key"}
    - { property: "<Alt>Tab", value: "cycle_windows_key"}
    - { property: "<Alt><Shift>Tab", value: "cycle_reverse_windows_key"}
    - { property: "<Super>Tab", value: "switch_window_key"}
    - { property: "<Primary><Alt>d", value: "show_desktop_key"}
    - { property: "<Primary><Alt>Up", value: "up_workspace_key"}
    - { property: "<Primary><Alt>Down", value: "down_workspace_key"}
    - { property: "<Primary><Alt>Home", value: "move_window_prev_workspace_key"}
    - { property: "<Primary><Alt>End", value: "move_window_next_workspace_key"}
    - { property: "<Primary><Alt>Page_Up", value: "raise_window_key"}
    - { property: "<Primary><Alt>Page_Down", value: "lower_window_key"}
    - { property: "Up", value: "up_key"}
    - { property: "Down", value: "down_key"}
    - { property: "Left", value: "left_key"}
    - { property: "Right", value: "right_key"}
    - { property: "Escape", value: "cancel_key"}
