---
## Create launcher in panel
- name: Make direcotry for launcher
  file:
    path: "{{ home }}.config/xfce4/panel/launcher-{{ launcher_plugin_id }}"
    state: directory
    mode: 0700

- name: Copy launcher for {{ package.name }} to my .config dir
  copy:
    src: "/usr/share/applications/{{ package.launcherName }}.desktop"
    dest: "{{ home }}.config/xfce4/panel/launcher-{{ launcher_plugin_id }}/{{ package.launcherName }}.desktop"
    remote_src: true

- name: "Add launcher as plugin-{{ launcher_plugin_id }} to xfce4-panel settings"
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/{{ pluginItem.property }}{{ pluginItem.subproperty }}"
    value_type: "{{ pluginItem.type }}"
    value: "{{ pluginItem.value }}"
    force_array: "{{ pluginItem.forcearray }}"
  loop:
    - { property: 'plugin-{{ launcher_plugin_id }}', subproperty: "", forcearray: false, type: string, value: "launcher" }
    - { property: 'plugin-{{ launcher_plugin_id }}', subproperty: "/items", forcearray: true, type: string, value: "{{ package.launcherName }}.desktop" }
  loop_control:
    loop_var: pluginItem

- set_fact:
    plugin_ids_array: "{{ plugin_ids_array + [ launcher_plugin_id ] }}"

- debug:
    var: plugin_ids_array

- name: "Add new launcher to panel"
  xfconf:
    channel: "xfce4-panel"
    property: "/panels/{{ launcher_panel_property }}/plugin-ids"
    value_type: int
    value: "{{ plugin_ids_array }}"
  register: panelValues

- name: increment launcher_plugin_id
  set_fact:
    launcher_plugin_id: "{{ launcher_plugin_id | int + 1 }}"
