---
- name: "Setup Launchers"
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/{{ item.property }}{{ item.subproperty }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
    force_array: "{{ item.forcearray }}"
  with_items:
  - { property: 'plugin-7', subproperty: "", forcearray: false, type: string, value: "launcher" }
  - { property: 'plugin-7', subproperty: "/items", forcearray: true, type: string, value: "15817800231.desktop" }
  - { property: 'plugin-56', subproperty: "", forcearray: false, type: string, value: "launcher" }
  - { property: 'plugin-56', subproperty: "/items", forcearray: true, type: string, value: "15986816841.desktop" }

