---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
      - ghactions
  # schedule:
  #   - cron: "0 0 * * 5"

jobs:

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the codebase.
  #       uses: actions/checkout@v2

  #     - name: Set up Python 3.
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'

  #     - name: Install test dependencies.
  #       run: pip3 install yamllint ansible-lint

  #     - name: Lint code.
  #       run: |
  #         yamllint .
  #         ansible-lint

  vagrant:
    name: Vagrant
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible passlib

      - name: Check out the codebase.
        uses: actions/checkout@v2

      # - uses: leleliu008/github-actions-vagrant@v1
      - name: Run github action - vagrant
        uses: ./.github/actions
        with:
          run: |
            echo "Hello from action"

      - name: Get roles
        run: ansible-galaxy install -r requirements.yaml

      - name: Add key fingerprint to known_hosts but don't login
        run: ssh-keyscan -H 172.16.3.22 >> ~/.ssh/known_hosts

      - name: Run 1. playbook
        run: ansible-playbook 1-setup_system.yaml --extra-vars '{"uid_guid":"1050"}' --extra-vars "variable_host=iosim"
