---
name: LINT
'on':
  pull_request:
  push:
    branches:
      - main
      - ghactions

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Get roles
        run: ansible-galaxy install -r requirements.yaml

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: List some stuff
        run: pwd

      - name: List some stuff 1
        run: ls ~/.ansible/roles
        continue-on-error: true

      - name: List some stuff 2
        run: ls /usr/share/ansible/roles
        continue-on-error: true

      - name: List some stuff 3
        run: ls /etc/ansible/roles
        continue-on-error: true

      - name: List some stuff 4
        run: ls roles
        continue-on-error: true

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .
        continue-on-error: true

      - name: List some stuff
        run: pwd

      - name: List some stuff 1
        run: ls ~/.ansible/roles
        continue-on-error: true

      - name: List some stuff 2
        run: ls /usr/share/ansible/roles
        continue-on-error: true

      - name: List some stuff 3
        run: ls /etc/ansible/roles
        continue-on-error: true

      - name: List some stuff 4
        run: ls roles
        continue-on-error: true
